# Spring config
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        host: localhost
        port: 5555
        name: shop_core
        username: shop_admin
        password: admin
    cache:
        type: none
    banner:
        location: classpath:/static/banner.txt # Graffiti
# Server config

server:
    servlet:
        contextPath: /api/v0
