# Shared config
spring:
    profiles:
        active: local
    jpa:
        database: postgresql
        properties.hibernate.jdbc.lob.non_contextual_creation: true
        open-in-view: false
    datasource:
        url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
    database:
        platform: postgres
        driverClassname: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    output.ansi.enabled: always
# Doc
springdoc:
    swagger-ui.path: /swagger-ui.html
    api-docs.path: /api-docs
# App info
app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
#Elastic apm
elastic.apm:
    service-name: ddd_example
    application-packages: org.dalvarez.ddd_example
