# Spring config
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        host: localhost
        port: 5555
        name: shop_core
        username: shop_admin
        password: admin
    cache:
        type: none
    banner:
        location: classpath:/banner.txt # Graffiti
# Server config
server:
    servlet:
        contextPath: /api/v0
    port: 8080
# Logging
logstash:
    host: localhost
    port: 5000
# Kafka
kafka:
    host: localhost
    port: 9092
#Elastic apm
elastic.apm:
    enabled: true
    server-url: http://localhost:8200
    secret-token: 99a4149d7fc04196ba0e25f067dde9cd
    environment: local
    log-level: INFO